[package]
name = "ruimads"
version = "0.1.0"
authors = ["tim"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.4.19"
itertools-num = "0.1.1"
rand = "0.7.3"
blas = "0.20.0"
openblas-src = "0.9"